export const USER_LOGIN = "USER_LOGIN"
export const FETCH_USER = "USER_FETCH"
export const FETCH_API = "FETCH_API"
export const FETCH_ALL_BOOKS = "FETCH_ALL_BOOKS"
export const FETCH_SUCCEDED = "FETCH_SUCCEDED"
export const FETCH_SUCCEDED_USER = "FETCH_SUCCEDED_USER"
export const FETCH_SELECTED_USER = "FETCH_SELECTED_USER"
export const SELECTED_USER = "SELECTED_USER"
export const FETCH_FAILED = "FETCH_FAILED"
export const SAVE_TOKEN = "SAVE_TOKEN"
export const CHECK_AUTH = "CHECK_AUTH"


